# Generated by Django 3.2.9 on 2021-12-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='experties',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
